// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using QuickType;
//
//    var raceSummarry = RaceSummarry.FromJson(jsonString);


using System.Text.Json.Serialization;

public partial class TestRaceSummary
{
    [JsonPropertyName("Season")]
    public int Season { get; set; }

    [JsonPropertyName("Round")]
    public int Round { get; set; }

    [JsonPropertyName("RaceName")]
    public string RaceName { get; set; }

    [JsonPropertyName("Date")]
    public string Date { get; set; }

    [JsonPropertyName("DriverLapTimes")]
    public TestDriverLapTime[] DriverLapTimes { get; set; }
}

public partial class TestDriverLapTime
{
    [JsonPropertyName("Id")]
    public string Id { get; set; }

    [JsonPropertyName("Driver")]
    public Driver Driver { get; set; }

    [JsonPropertyName("LapTimes")]
    public TestLapTime[] LapTimes { get; set; }
}

public partial class TestLapTime
{
    [JsonPropertyName("LapNumber")]
    public int LapNumber { get; set; }

    [JsonPropertyName("DriverId")]
    public string DriverId { get; set; }

    [JsonPropertyName("Position")]
    public int Position { get; set; }

    [JsonPropertyName("Time")]
    public double Time { get; set; }
}


